<?php include "header.php"; ?>

<div class="subheader">
    <div class="container">
        <div class="subheader-inner">
            <h2 class="subheader-title">All About Solar</h2>
        </div>
    </div>
</div>
<!--About-->

<section class="section about-sec about-wraps">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="about-content">
    <div class="about-title">

    <h1 class="">Rooftop Solar Technology</h1>
    </div>

    <p>Rooftop solar technology is one of the most efficient and reliable ways to generate clean and sustainable energy. When sunlight falls on solar panels installed on residential, commercial, or industrial rooftops, the photovoltaic cells inside the modules convert the sunlight into direct current (DC) electricity. This electricity is then used to power the building’s electrical needs. Solar panels are specially designed to capture solar energy and transform it into usable power through advanced photovoltaic technology. The generated DC power is sent to an inverter, which converts it into alternating current (AC) for everyday use. Any surplus electricity can either be stored in batteries or exported to the grid for future consumption. At Evaska Energy, you can find the ideal rooftop solar solution tailored to your home’s requirements.</p>

    <p>It is important to understand that the electricity produced by your rooftop solar plant can work alongside the power supplied by your local DISCOM. Such grid-connected systems are widely adopted and professionally managed by experienced solar installers. For industrial applications, larger solar systems provide enhanced efficiency and output. If you prefer backup support for nighttime usage, hybrid or off-grid systems with battery storage are excellent alternatives. Evaska Energy also offers cost-effective solar panel kits designed specifically for residential needs.</p>

    <p>In areas where net metering approvals are delayed or unavailable, customers can opt for a Zero Export Device (Z.E.D) to start reducing high electricity bills from the very first day. Choose Evaska Energy’s reliable solar solutions for your home today.</p>

    <p>For locations facing delays in <a style="color: #ff8a00;" href="https://www.corvelsolar.com/blog/net-energy-metering-benefits-and-how-it-works">net metering</a> or lacking net metering facilities, installing a Zero Export Device (Z.E.D) ensures you can immediately begin saving on substantial electricity costs. Explore Evaska Energy’s <a href="https://www.corvelsolar.com/blog/cost-of-power-solar-rooftop-panels-for-homes-in-gurgaon">solar panel system for home</a> and make the switch to clean energy today.</p>

</div>

            </div>
            <div class="col-lg-6">
                <div class="about-image">
                    <img src="img/about-1.PNG" alt="Rooftop solar energy" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</section>

<!--How it works-->

<section class="section process-sec pt-0">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="process-image text-center">
                    <img src="https://www.corvelsolar.com/website/assets/img/about/about.webp" alt="Rooftop solar energy">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="process-content">
                    <div class="d-flex align-items-center section-title">
                        <img src="https://www.corvelsolar.com/website/assets/img/about/icon-2.png" class="mr-2" alt="Rooftop solar energy">
                        <h2 class="title">"How Solar Energy Works"?</h2>
                    </div>
                    <ul class="process-list">
                        <li>
                            <i class="fa fa-check"></i>
                            The sunlight that falls on the solar panels causes them to generate power.

                        </li>
                        <li>
                            <i class="fa fa-check"></i>
                            The DC cable transports the direct current generated by the solar panels to the solar inverter.
                        </li>
                        <li>
                            <i class="fa fa-check"></i>
                            The solar inverter is the main component of the solar system that converts Direct Current (DC) to Alternating Current (AC) for use by the premises' appliances.

                        </li>
                        <li>
                            <i class="fa fa-check"></i>
                            The junction box in the solar system installation serves as a protection device for the solar system installed, ensuring that it is not disrupted.

                        </li>
                        <li>
                            <i class="fa fa-check"></i>
                            Use free solar energy to power all of your heavy loads, such as air conditioners, geysers, and machines, as ell as light loads, such as fans, televisions, lights, and refrigerators.

                        </li>
                        <li>

                        <li>
                            <i class="fa fa-check"></i>
                            Whatever quantity of power generated by the solar system is not utilised by you in the same month is returned to the grid and may be used by you the following month to minimise your electric bill and become energy independent.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<!--Solar category-->

<section class="section solar-category-sec pt-0">
    <div class="container">
        <div class="section-title text-center">
            <img src="https://www.corvelsolar.com/website/assets/img/about/icon-2.png" class="mb-4" alt="Rooftop solar energy">
            <h2 class="title">Different types of Solar Plants:</h2>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="category-block">
                    <div class="category-block-inner">
                        <div class="category-thumb">
                            <img src="https://www.corvelsolar.com/website/assets/img/about/about-2.jpg" alt="Rooftop solar energy">
                        </div>
                        <div class="category-content">
                            <h4>ON Grid Solar Plant</h4>
                            <p>It is a grid-connected solar power plant that uses the electricity grid as a primary source and needs no battery backup for storing excess energy. It is comparatively a more cost-effective form of the solar power plant.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="category-block">
                    <div class="category-block-inner">
                        <div class="category-thumb">
                            <img src="https://www.corvelsolar.com/website/assets/img/about/about-3.jpg" alt="Rooftop solar energy">
                        </div>
                        <div class="category-content">
                            <h4>Hybrid Solar Plant</h4>
                            <p>It is a solar plant which has the capability to store excess electricity inside the batteries. The inverters used in these systems differ also they have batteries in extra which can provide backup for somewhere between 8 to 10 hours. Also, it is comparatively expensive than ON Grid Solar Plant.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="category-block">
                    <div class="category-block-inner">
                        <div class="category-thumb">
                            <img src="https://www.corvelsolar.com/website/assets/img/about/about-4.jpg" alt="Rooftop solar energy">
                        </div>
                        <div class="category-content">
                            <h4>OFF Grid Solar Plant</h4>
                            <p>They are somewhat similar to Hybrid Solar Plant but the main difference is they are installed in places with no Grid support and are known as stand-alone system with extra batteries and a longer back up time period.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
<style>
    .about-sec a {
        color: #ff8a00 !important;
    }
</style>
<?php include "footer.php"; ?>